#!/usr/bin/env python3
"""Statistical companion to the master table, at the deepest configuration.

The master table is relL2 only. This one carries the physical metrics, which is
where the perception-distortion split actually shows up: biharmonic has the
WORST relL2 of any method and the BEST distributional scores.

Wasserstein-1 is deliberately absent -- it moves 17.8% between replicates
(78.5% at worst), the least reproducible quantity measured. KL moves 10.4%.

    python make_stats_table.py > Thesis/figures/tab_stats.tex
"""
import csv, sys

CELL = ("single", "25")          # deepest: 64 px, 4.57 correlation lengths
# THE PLAIN RECIPE IS THE ONE WE REPORT, changed 2026-08-30. The original nine
# runs had the x-shift augmentation and weight averaging on; the re-trained set has
# both off, and so does every centre-trained run (the aux ablation, the objective
# control). Reporting the newer set makes the whole thesis one population. The two
# differ by 3.3% on average, inside the 4.2% replicate floor, which is precisely
# why that pair is what the floor is measured from.
RECIPE, TRAIN = "plain", "random"

_all = list(csv.DictReader(open("figures/metrics_si_inpaint.csv")))
si = [r for r in _all
      if r["aux"] == "-" and r["recipe"] == RECIPE and r["train"] == TRAIN]

# The U-Net objective control is looked up WITHOUT the train filter, for the same
# reason as in make_master_table.py: the filter above pins train=random because
# that is this table's population, and a centre-trained control would be dropped
# silently rather than visibly. The dagger appears only while the control's
# training position differs from the rest of the table, and disappears on its own
# once a random-trained run exists at this cell.
fno = [r for r in _all if r["model"] == "FNO" and r["aux"] == "-"]
unet_rows = [r for r in _all if r["model"].startswith("U-Net") and r["aux"] == "-"]
bl = list(csv.DictReader(open("figures/metrics_baselines.csv")))

def pick(rows, **f):
    """Best (lowest relL2) matching row at the target cell. For gappy POD this
    selects the best rank, as the chapter states."""
    v = [r for r in rows if (r["geom"], r["gap"]) == CELL
         and all(r[k] == vv for k, vv in f.items())]
    return min(v, key=lambda r: float(r["relL2"])) if v else None

unet = pick(unet_rows)
unet_mixed = unet is not None and unet["train"] != TRAIN

def _gpod_label(r):
    return "gappy POD" if r is None else "gappy POD (rank %s)" % r["rank"]


ROWS = [("zero fill",  pick(bl, method="zero")),
        ("harmonic",   pick(bl, method="harmonic")),
        ("biharmonic", pick(bl, method="biharmonic")),
        # THE RANK IS PRINTED, not hidden. This row is selected on relL2 across ten
        # ranks, and the top two can sit 0.24% apart -- far inside the 4.2% replicate
        # floor -- so which rank wins is effectively arbitrary. The other columns
        # then come from whichever row won, and they are NOT close: rank 2 and rank
        # 4 differ by 21% in KL. Naming the rank lets a reader see that the physical
        # columns belong to one particular fit rather than to "gappy POD" in general.
        (_gpod_label(pick(bl, method="gpod")),  pick(bl, method="gpod")),
        ("FNO",        pick(fno)),
        ("interpolant", pick(si, model="SI"))]

# THE OBJECTIVE CONTROL AND ITS MATCHED PARTNER, appended as a pair. The U-Net is
# centre-trained and every row above is random-trained, so putting it beside the
# random-trained interpolant would invite a reader to compare across training
# positions -- and the prose would then have to quote different numbers from the
# ones printed here. Adding the centre-trained interpolant fixes that: the last two
# rows are a like-for-like pair differing in the objective alone, and the dagger
# says so. Drop both rows and the dagger once a random-trained U-Net exists.
si_ctr = [r for r in _all if r["model"] == "SI" and r["aux"] == "-"
          and r["train"] == "center"]
if unet is not None:
    mark = "$^{\\dagger}$" if unet_mixed else ""
    ROWS += [("interpolant" + mark, pick(si_ctr)), ("U-Net" + mark, unet)]

COLS = [("\\relL{}", "relL2", "1.3"), ("correlation", "corr_in", "1.3"),
        ("std ratio", "std_in", "1.3"), ("enstrophy ratio", "enstr_in", "1.3"),
        ("KL", "kl_in", "2.3"), ("W1", "w1_in", "1.3")]

def cell(r, k):
    v = r.get(k, "")
    if v in ("", "nan"):        # zero fill has no correlation: constant field
        return "{--}"
    return "%.3f" % float(v)

o = sys.stdout
o.write("% GENERATED by make_stats_table.py -- do not edit by hand.\n")
o.write("\\begin{table}[htbp]\n  \\centering\n")
o.write("  \\caption[In-void metrics at the deepest configuration]{Every method at\n"
        "  the deepest configuration, single square at $25\\%$ coverage, $64$\\,px.\n"
        "  Ratios are prediction over truth."
        + (" The last two rows\n"
           "  are trained on the centred mask rather than the random placement used by\n"
           "  every row above." if unet_mixed else "")
        + "}\n")
o.write("  \\label{tab:stats}\n")
o.write("  \\resizebox{\\ifdim\\width>\\textwidth\\textwidth\\else\\width\\fi}{!}{%\n")
o.write("  \\begin{tabular}{l" + "".join("S[table-format=%s]" % f for _, _, f in COLS) + "}\n")
o.write("    \\toprule\n    method & " + " & ".join("{%s}" % n for n, _, _ in COLS) + " \\\\\n")
o.write("    \\midrule\n")
for name, r in ROWS:
    if r is None:
        continue
    o.write("    %-12s & " % name + " & ".join(cell(r, k) for _, k, _ in COLS) + " \\\\\n")
o.write("    \\bottomrule\n  \\end{tabular}}\n\\end{table}\n")
