#!/usr/bin/env python
"""Generate the complete metric tables for appendix B.

    python make_full_tables.py            # -> Thesis/figures/tab_full_*.tex

WHY A GENERATOR AND NOT HAND-TYPED. tab:sweep was hand-typed once and silently
kept pre-recipe-switch values through a whole rewrite; the same class of error
put a stale 10.2% into the Shu section. Every number below is read from the CSVs
at build time, so the appendix cannot disagree with the eval.

THREE TABLES, because they answer different questions:
  tab_full_learned    every learned run, all in-void metrics. The results chapter
                      shows relL2 for all nine cells (tab:master) and the other
                      metrics for ONE cell (tab:stats); this is the rest.
  tab_full_classical  zero / harmonic / biharmonic across all ten configurations.
  tab_full_gpod       the gappy-POD rank sweep and the oracle bound. The oracle is
                      the projection of the truth onto the same basis, so it is the
                      ceiling no fitting procedure using that basis can beat.

WRITE TO A TEMP FILE AND MOVE. A previous generator failure emptied tab_stats.tex
because the caller redirected stdout straight onto the live file.
"""
import csv
import os
import sys

SI_CSV = "figures/metrics_si_inpaint.csv"
BL_CSV = "figures/metrics_baselines.csv"
OUTDIR = "Thesis/figures"

# The recipe reported throughout the thesis. The other population exists in the CSV
# and is NOT shown here -- see the note printed at the end.
RECIPE = "plain"

# (column, header, format). Chosen to match tab:stats so a reader can move between them.
COLS = [
    ("relL2",    r"\relL{}",        "%.3f"),
    ("corr_in",  "corr",            "%.3f"),
    ("std_in",   "std",             "%.3f"),
    ("enstr_in", "enstr",           "%.3f"),
    ("e_spec_in", "spec",           "%.3f"),
    ("mae_g_in", "grad",            "%.3f"),
    ("kl_in",    "KL",              "%.3f"),
    ("w1_in",    "W1",              "%.3f"),
]

GEOM_TEX = {"single": "single", "multiple": "multiple", "random": "random"}


def num(r, key, fmt):
    v = r.get(key, "")
    if v in ("", "nan", "NaN", None):
        return "{--}"
    try:
        f = float(v)
    except ValueError:
        return "{--}"
    if f != f:                      # NaN
        return "{--}"
    return fmt % f


def cfg_label(r):
    n = r.get("n_voids", "") or "1"
    return "%s $\\times$ %s\\%%" % (GEOM_TEX.get(r["geom"], r["geom"]), r["gap"]) \
        if n in ("", "1") else \
        "%s ($n{=}%s$) $\\times$ %s\\%%" % (GEOM_TEX.get(r["geom"], r["geom"]), n, r["gap"])


def header(caption, short, label, ncol, nlabel=2):
    spec = "l" * nlabel + "S[table-format=1.3]" * ncol
    return (
        "\\begin{table}[htbp]\n  \\centering\n"
        "  \\caption[%s]{%s}\n  \\label{%s}\n" % (short, caption, label)
        + "  \\resizebox{\\ifdim\\width>\\textwidth\\textwidth\\else\\width\\fi}{!}{%\n"
        "  \\begin{tabular}{" + spec + "}\n    \\toprule\n"
    )


FOOT = "    \\bottomrule\n  \\end{tabular}}\n\\end{table}\n"


def write(name, body):
    os.makedirs(OUTDIR, exist_ok=True)
    path = os.path.join(OUTDIR, name)
    tmp = path + ".tmp"
    with open(tmp, "w") as f:
        f.write("%% GENERATED by make_full_tables.py -- do not edit by hand.\n")
        f.write(body)
    os.replace(tmp, path)
    print("wrote %s" % path)


# ---------------------------------------------------------------- learned runs
def learned():
    rows = list(csv.DictReader(open(SI_CSV)))
    # The FNO runner writes no recipe suffix, so its label is an artefact and
    # filtering it by RECIPE would empty the column. Same special case as
    # make_master_table.py and make_stats_table.py.
    keep = [r for r in rows if r["recipe"] == RECIPE or r["model"] == "FNO"]
    keep.sort(key=lambda r: (float(r["depth"]), r["model"], r["aux"], r["train"]))

    out = header(
        "Every learned run at the reported recipe, scored in the void. "
        "\\relL{} is also in \\cref{tab:master}; the remaining columns appear in the "
        "results chapter for one configuration only (\\cref{tab:stats}). "
        "Ratios are prediction over truth. Spectral entries are blank where the "
        "void is not a single block.",
        "All learned runs", "tab:full-learned", len(COLS), nlabel=3)
    out += ("    depth & configuration & run & "
            + " & ".join("{%s}" % h for _, h, _ in COLS)
            + " \\\\\n    \\midrule\n")
    # Depth alone does not identify a row: at 8 px and at 32 px the design has two
    # coverages, which is the whole point of the crossed design. The configuration
    # column is what keeps those apart.
    last = None
    for r in keep:
        d = "%d" % float(r["depth"])
        dcell = d if d != last else ""
        last = d
        aux = "" if r["aux"] in ("-", "") else ", %s" % r["aux"]
        run = "%s (%s%s)" % (r["model"], r["train"], aux)
        out += "    %s & %s & %s & %s \\\\\n" % (
            dcell, cfg_label(r), run, " & ".join(num(r, c, f) for c, _, f in COLS))
    return out + FOOT


# ------------------------------------------------------------------- classical
def classical():
    rows = [r for r in csv.DictReader(open(BL_CSV))
            if r["method"] in ("zero", "harmonic", "biharmonic")]
    rows.sort(key=lambda r: (float(r["depth"]), r["method"]))
    out = header(
        "The classical fills on every configuration, scored in the void. "
        "Zero fill is the do-nothing reference: its \\relL{} is $1.000$ by "
        "construction, so a method scoring above it is worse than predicting "
        "nothing at all.",
        "Classical fills, all configurations", "tab:full-classical", len(COLS),
        nlabel=3)
    out += ("    depth & configuration & method & "
            + " & ".join("{%s}" % h for _, h, _ in COLS)
            + " \\\\\n    \\midrule\n")
    last = None
    for r in rows:
        d = "%d" % float(r["depth"])
        dcell = d if d != last else ""
        last = d
        out += "    %s & %s & %s & %s \\\\\n" % (
            dcell, cfg_label(r), r["method"],
            " & ".join(num(r, c, f) for c, _, f in COLS))
    return out + FOOT


# ----------------------------------------------------------------- gappy POD
def gpod():
    rows = list(csv.DictReader(open(BL_CSV)))
    ranks = sorted({int(r["rank"]) for r in rows if r["method"] == "gpod"})
    cfgs = sorted({(float(r["depth"]), r["geom"], r["gap"], r["n_voids"])
                   for r in rows if r["method"] == "gpod"})
    idx = {(r["method"], int(r["rank"]), r["geom"], r["gap"], r["n_voids"]): r
           for r in rows if r["method"] in ("gpod", "pod_oracle")}

    spec = "l" + "S[table-format=1.3]" * len(ranks) + "S[table-format=1.3]"
    out = ("\\begin{table}[htbp]\n  \\centering\n"
           "  \\caption[Gappy POD rank sweep]{In-void \\relL{} for gappy POD at every "
           "rank, with the oracle bound in the last column. The oracle is the "
           "projection of the truth onto the same basis, so no fitting procedure "
           "using that basis can beat it. Where the sweep exceeds the oracle the "
           "failure is the fit, and where the oracle itself is poor the failure is "
           "the basis.}\n"
           "  \\label{tab:full-gpod}\n"
           "  \\resizebox{\\ifdim\\width>\\textwidth\\textwidth\\else\\width\\fi}{!}{%\n"
           "  \\begin{tabular}{" + spec + "}\n    \\toprule\n")
    out += ("    configuration & " + " & ".join("{%d}" % k for k in ranks)
            + " & {oracle} \\\\\n    \\midrule\n")
    for depth, geom, gap, nv in cfgs:
        cells = []
        for k in ranks:
            r = idx.get(("gpod", k, geom, gap, nv))
            cells.append(num(r, "relL2", "%.3f") if r else "{--}")
        best = None
        for k in ranks:
            r = idx.get(("pod_oracle", k, geom, gap, nv))
            if r:
                v = float(r["relL2"])
                best = v if best is None or v < best else best
        cells.append("%.3f" % best if best is not None else "{--}")
        lbl = "%s, %s\\%% (%d\\,px)" % (GEOM_TEX.get(geom, geom), gap, depth)
        out += "    %s & %s \\\\\n" % (lbl, " & ".join(cells))
    return out + FOOT


if __name__ == "__main__":
    for f in (SI_CSV, BL_CSV):
        if not os.path.exists(f):
            sys.exit("missing %s -- run the eval and rsync the CSVs first" % f)
    write("tab_full_learned.tex", learned())
    write("tab_full_classical.tex", classical())
    write("tab_full_gpod.tex", gpod())
    n_other = sum(1 for r in csv.DictReader(open(SI_CSV))
                  if r["recipe"] != RECIPE and r["model"] != "FNO")
    print("\nNOTE: %d rows at the other recipe are in the CSV and are NOT tabulated."
          % n_other)
    print("      The thesis reports recipe=%r throughout; showing both would invite"
          % RECIPE)
    print("      a reader to compare across populations. Change RECIPE to switch.")
