#!/usr/bin/env python3
"""Emit the master comparison table as LaTeX, straight from the metric CSVs.

Never hand-copy numbers into the thesis: run this and \\input the result. The
chapter's own instruction is that every number comes from the CSVs.

    python make_master_table.py > Thesis/figures/tab_master.tex
"""
import csv, sys

SI_CSV = "figures/metrics_si_inpaint.csv"
BL_CSV = "figures/metrics_baselines.csv"
RECIPE, TRAIN = "ema+xshift", "random"

si = [r for r in csv.DictReader(open(SI_CSV))
      if r["aux"] == "-" and r["recipe"] == RECIPE and r["train"] == TRAIN]
bl = list(csv.DictReader(open(BL_CSV)))

cell = lambda r: (r["geom"], r["gap"])
cells = sorted({cell(r) for r in si},
               key=lambda c: (float(next(r["depth"] for r in si if cell(r) == c)),
                              float(c[1])))          # depth, then coverage, so ties are stable

def best(rows, c, **f):
    """Lowest relL2 among matching rows. For gappy POD this picks the best
    rank, which is the deliberately generous choice the chapter states."""
    v = [r for r in rows if cell(r) == c and all(r[k] == vv for k, vv in f.items())]
    return min((float(r["relL2"]) for r in v), default=None)

COLS = [("zero fill",  lambda c: best(bl, c, method="zero")),
        ("harmonic",   lambda c: best(bl, c, method="harmonic")),
        ("biharmonic", lambda c: best(bl, c, method="biharmonic")),
        ("gappy POD",  lambda c: best(bl, c, method="gpod")),
        ("FNO",        lambda c: best(si, c, model="FNO")),
        ("SI",         lambda c: best(si, c, model="SI"))]

out = sys.stdout
out.write("% GENERATED by make_master_table.py -- do not edit by hand.\n")
out.write("\\begin{table}[htbp]\n  \\centering\n")
out.write("  \\caption[Every method on every configuration]{In-void \\relL{} for\n"
          "  every method on all nine configurations, ordered by depth. Gappy POD is\n"
          "  quoted at its best rank. Zero fill is $1.000$ by construction, which\n"
          "  checks the evaluation path.}\n")
out.write("  \\label{tab:master}\n")
out.write("  \\begin{tabular}{llS[table-format=2.0]" + "S[table-format=1.3]" * len(COLS) + "}\n")
out.write("    \\toprule\n    geometry & coverage & {depth (px)} & "
          + " & ".join("{%s}" % n for n, _ in COLS) + " \\\\\n    \\midrule\n")
for c in cells:
    depth = float(next(r["depth"] for r in si if cell(r) == c))
    vals = [f(c) for _, f in COLS]
    out.write("    %-9s & %s\\%% & %.0f & " % (c[0], c[1], depth)
              + " & ".join("%.3f" % v if v is not None else "{--}" for v in vals)
              + " \\\\\n")
out.write("    \\bottomrule\n  \\end{tabular}\n\\end{table}\n")
