#!/usr/bin/env python
"""Compute the replicate noise floors and emit them as LaTeX macros.

    python make_floors.py > Thesis/figures/floors.tex

WHY THIS EXISTS. The floors were hand-typed from a run made on the 37-row CSV.
The CSV now has 49 rows, and recomputing gives 4.4/6.8 where the prose says
4.2/6.4. Every chapter quotes these numbers, so a hand-typed floor is exactly
the kind of thing that goes stale silently -- the same failure as tab:sweep and
the 10.2% same-depth spread. Generating them means the prose cannot drift from
the eval.

MEDIAN AND WORST, BOTH. A single floor per metric is what caused the ablation
prose to contradict its own table: the medians resolve seven of eight auxiliary
runs, the worst case resolves four. The median says what a typical retraining
moves; the worst says what we can defend. Claims in the results chapter are
tested against the WORST, because a floor that only holds on average is not a
floor.

THE PAIRS. Nine configurations, each trained twice under a change of defaults
that moved nothing (mean ratio 0.997), so the two runs are replicates of the
same model. In-void spectral error exists for box geometries only, so its floor
rests on five pairs rather than nine -- which is itself a reason not to lean on
it.
"""
import collections
import csv
import statistics
import sys

CSV = "figures/metrics_si_inpaint.csv"

METRICS = [("relL2",     "relLtwo",  "\\relL{}"),
           ("corr_in",   "corr",     "in-void correlation"),
           ("std_in",    "std",      "standard deviation"),
           ("enstr_in",  "enstr",    "enstrophy"),
           ("e_spec_in", "spec",     "in-void spectral error"),
           ("kl_in",     "kl",       "KL divergence"),
           ("w1_in",     "wone",     "Wasserstein-1")]


def pairs(rows):
    pop = collections.defaultdict(dict)
    for x in rows:
        if x["model"] != "SI" or x["aux"] not in ("-", ""):
            continue
        k = (x["depth"], x["geom"], x["gap"], x["n_voids"], x["train"])
        pop[k][x["recipe"]] = x
    return [(v["plain"], v["ema+xshift"]) for v in pop.values() if len(v) == 2]


def main():
    rows = list(csv.DictReader(open(CSV)))
    pr = pairs(rows)
    if not pr:
        sys.exit("no replicate pairs found -- both recipes must be in the CSV")

    out = sys.stdout
    out.write("%% GENERATED by make_floors.py -- do not edit by hand.\n")
    out.write("%% Replicate floors from %d pairs. Median and worst per metric.\n"
              % len(pr))
    stderr = []
    for key, macro, _ in METRICS:
        d = []
        for a, b in pr:
            try:
                va, vb = float(a[key]), float(b[key])
            except ValueError:
                continue
            if va != va or vb != vb or va == 0:
                continue
            d.append(100.0 * abs(vb - va) / abs(va))
        if not d:
            continue
        med, worst = statistics.median(d), max(d)
        out.write("\\newcommand{\\floor%s}{%.1f}\n" % (macro, med))
        out.write("\\newcommand{\\floorworst%s}{%.1f}\n" % (macro, worst))
        stderr.append((key, med, worst, len(d)))

    sys.stderr.write("\n  metric        median   worst    pairs\n")
    for key, med, worst, n in stderr:
        sys.stderr.write("  %-12s %6.1f%% %7.1f%%   %d\n" % (key, med, worst, n))
    sys.stderr.write("\nUse \\floorX in prose for the typical figure and "
                     "\\floorworstX where a claim must hold.\n")


if __name__ == "__main__":
    main()
