#!/usr/bin/env python3
"""Emit the external-benchmark table: our runs beside Shu et al.'s Table 1.

    python make_shu_table.py > Thesis/figures/tab_shu.tex

SHU_TABLE1 IS IMPORTED, NOT RETYPED. Their three rows already live in
eval_si_inpaint.py, read from the paper once and checked there. Copying them into
a second file is how a thesis ends up quoting a number the eval disagrees with,
and here the numbers are someone else's published results -- getting one wrong is
worse than getting our own wrong.

WHICH OF OUR ROWS. Shu et al. train on a FIXED mask, so our centre-trained runs
are the like-for-like ones and this table uses them. Our headline rows are
trained on a re-rolled void, which is the harder task; quoting those instead
flatters the growth-factor agreement (1.9% apart rather than 4.8%) and it
contradicts the very protocol argument that justifies the comparison. Do not
switch this to train=random for a better-looking number.

COVERAGE IS IDENTICAL ACROSS ALL THREE ROWS AND EQUAL TO THEIRS, which is what
makes the comparison a comparison. 1x128^2, 4x64^2 and 16x32^2 each remove
16,384 of 65,536 pixels, i.e. exactly 25%. The script asserts this rather than
trusting it, because the whole argument of the section rests on it.
"""
import csv
import sys

sys.path.insert(0, ".")
from eval_si_inpaint import SHU_TABLE1                                # noqa: E402

CSV = "figures/metrics_si_inpaint.csv"
TOTAL_PX = 256 * 256

rows = list(csv.DictReader(open(CSV)))


def ours(geom, gap, n):
    """Our centre-trained, plain-objective run at this arrangement."""
    v = [r for r in rows
         if (r["geom"], r["gap"], r["n_voids"]) == (geom, str(gap), str(n))
         and r["model"] == "SI" and r["aux"] == "-" and r["train"] == "center"]
    return v[0] if v else None


out = sys.stdout
out.write("% GENERATED by make_shu_table.py -- do not edit by hand.\n")
out.write("\\begin{table}[htbp]\n  \\centering\n")
out.write("  \\caption[Against Shu et al.\\ Table 1]{Our centre-trained runs beside\n"
          "  the three rows of \\citet{shu2024inpainting} Table~1. Lower is better,\n"
          "  and $1.000$ is the score for predicting nothing.}\n")
out.write("  \\label{tab:shu}\n")
out.write("  \\begin{tabular}{llS[table-format=2.0]S[table-format=1.3]"
          "S[table-format=1.3]S[table-format=1.3]S[table-format=1.3]}\n")
out.write("    \\toprule\n")
out.write("    & & {depth} & {ours} & \\multicolumn{3}{c}{\\citet{shu2024inpainting}} \\\\\n")
out.write("    \\cmidrule(lr){5-7}\n")
out.write("    arrangement & coverage & {(px)} & {interpolant} & {VQ-VAE} & {FNO}"
          " & {FactFormer} \\\\\n    \\midrule\n")

for geom, gap, n, vq, fno, ff in SHU_TABLE1:
    side = int((gap / 100 * TOTAL_PX / n) ** 0.5)
    removed = n * side * side
    # The claim the section rests on, checked rather than asserted.
    assert abs(removed / TOTAL_PX * 100 - gap) < 0.01, \
        "%d x %d^2 removes %d px, not %g%% of %d" % (n, side, removed, gap, TOTAL_PX)
    r = ours(geom, gap, n)
    cell = "{--}" if r is None else "%.3f" % float(r["relL2"])
    depth = "{--}" if r is None else "%.0f" % float(r["depth"])
    out.write("    $%d \\times %d^2$ & %g\\%% & %s & %s & %.3f & %.3f & %.3f \\\\\n"
              % (n, side, gap, depth, cell, vq, fno, ff))

out.write("    \\bottomrule\n  \\end{tabular}\n\\end{table}\n")
