#!/usr/bin/env python3
"""Statistical companion to the master table, at the deepest configuration.

The master table is relL2 only. This one carries the physical metrics, which is
where the perception-distortion split actually shows up: biharmonic has the
WORST relL2 of any method and the BEST distributional scores.

Wasserstein-1 is deliberately absent -- it moves 17.8% between replicates
(78.5% at worst), the least reproducible quantity measured. KL moves 10.4%.

    python make_stats_table.py > Thesis/figures/tab_stats.tex
"""
import csv, sys

CELL = ("single", "25")          # deepest: 64 px, 4.57 correlation lengths
RECIPE, TRAIN = "ema+xshift", "random"

si = [r for r in csv.DictReader(open("figures/metrics_si_inpaint.csv"))
      if r["aux"] == "-" and r["recipe"] == RECIPE and r["train"] == TRAIN]
bl = list(csv.DictReader(open("figures/metrics_baselines.csv")))

def pick(rows, **f):
    """Best (lowest relL2) matching row at the target cell. For gappy POD this
    selects the best rank, as the chapter states."""
    v = [r for r in rows if (r["geom"], r["gap"]) == CELL
         and all(r[k] == vv for k, vv in f.items())]
    return min(v, key=lambda r: float(r["relL2"])) if v else None

ROWS = [("zero fill",  pick(bl, method="zero")),
        ("harmonic",   pick(bl, method="harmonic")),
        ("biharmonic", pick(bl, method="biharmonic")),
        ("gappy POD",  pick(bl, method="gpod")),
        ("FNO",        pick(si, model="FNO")),
        ("interpolant", pick(si, model="SI"))]

COLS = [("\\relL{}", "relL2", "1.3"), ("correlation", "corr_in", "1.3"),
        ("std ratio", "std_in", "1.3"), ("enstrophy ratio", "enstr_in", "1.3"),
        ("KL", "kl_in", "2.3")]

def cell(r, k):
    v = r.get(k, "")
    if v in ("", "nan"):        # zero fill has no correlation: constant field
        return "{--}"
    return "%.3f" % float(v)

o = sys.stdout
o.write("% GENERATED by make_stats_table.py -- do not edit by hand.\n")
o.write("\\begin{table}[htbp]\n  \\centering\n")
o.write("  \\caption[Pointwise against physical fidelity]{Every method at the\n"
        "  deepest configuration, single square at $25\\%$ coverage, $64$\\,px. Ratios\n"
        "  are prediction over truth, so unity is correct. Biharmonic has the worst\n"
        "  \\relL{} of any method here and the best distributional scores, which is the\n"
        "  ranking reversal a pointwise-only protocol would miss.}\n")
o.write("  \\label{tab:stats}\n")
o.write("  \\begin{tabular}{l" + "".join("S[table-format=%s]" % f for _, _, f in COLS) + "}\n")
o.write("    \\toprule\n    method & " + " & ".join("{%s}" % n for n, _, _ in COLS) + " \\\\\n")
o.write("    \\midrule\n")
for name, r in ROWS:
    if r is None:
        continue
    o.write("    %-12s & " % name + " & ".join(cell(r, k) for _, k, _ in COLS) + " \\\\\n")
o.write("    \\bottomrule\n  \\end{tabular}\n\\end{table}\n")
